# Board: Espressif ESP32-S3-DevKitM-1 (Espressif)
# Definition: definitions/boards/esp32-s3-devkitm-1/manifest.yaml
substitutions:
  tx_pin: GPIO12
  rx_pin: GPIO13
  fc_pin: GPIO11
  name: jk-bms
  esp_name: ESP-BMS
  bms0_name: BMS-rechts
  bms1_name: BMS-links

esphome:
  name: $name
  friendly_name: jkbms
  project:
    name: "ajvdw.esphome-jk-bms"
    version: 1.0.0
  devices:
    - id: bms_device_0
      name: $bms0_name
    - id: bms_device_1
      name: $bms1_name

    
esp32:
  variant: esp32s3
#  flash_size: 8MB
  framework:
    type: esp-idf

api:
  encryption: 
      key: !secret api_encryption_key

# Note: The uart settings depend on the Modbus configuration of the system that you connect it to
# flow: 11, tx: 12, rx: 13

logger:
  level: WARN #not more because of delays
  tx_buffer_size: 2048
ota:
  platform: esphome
  password: !secret ota_password      # https://esphome.io/guides/security_best_practices/#using-secretsyaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  source: github://ajvdw/esphome-jk-bms@main
  refresh: 0s
#  components: [jk_rs485_sniffer , jk_rs485_bms]

uart: 
  - id: uart_0
    tx_pin: $tx_pin
    rx_pin: $rx_pin
    rx_buffer_size: 384  
    baud_rate: 115200

jk_rs485_sniffer:
  - id: sniffer0
    protocol_version: "JK02_32S"
    rx_timeout: 500ms
    uart_id: uart_0
 #   talk_pin: ${fc_pin}
    

jk_rs485_bms:
  - id: bms0
    rs485_address: 0x00
    jk_rs485_sniffer_id: sniffer0
    update_interval: 180s
  - id: bms1
    rs485_address: 0x01
    jk_rs485_sniffer_id: sniffer0
    update_interval: 180s

    
sensor:
  - platform: uptime
    id: uptime_sec
  # +--------------------------------------+
  # | Uptime sensor                        |
  # +--------------------------------------+
  - platform: uptime
    name: ${esp_name} Uptime Sensor
    id: uptime_sensor
    update_interval: 5s
    entity_category: diagnostic

  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms0
    balancing_direction:
      name: "balancing direction"
      device_id: bms_device_0
    battery_capacity_setting:
      name: "battery capacity setting"
      device_id: bms_device_0
    cell_voltage_min:
      name: "cell voltage min"
      device_id: bms_device_0
    cell_voltage_max:
      name: "cell voltage max"
      device_id: bms_device_0
    cell_voltage_min_cell_number:
      name: "cell voltage min cell number"
      device_id: bms_device_0
    cell_voltage_max_cell_number:
      name: "cell voltage max cell number"
      device_id: bms_device_0
    cell_delta_voltage:
      name: "cell delta voltage"
      device_id: bms_device_0
    cell_average_voltage:
      name: "cell average voltage"
      device_id: bms_device_0
    cell_resistance_min:
      name: "cell resistance min"
      device_id: bms_device_0
    cell_resistance_max:
      name: "cell resistance max"      
      device_id: bms_device_0
    cell_resistance_min_cell_number:
      name: "cell resistance min cell number"
      device_id: bms_device_0
    cell_resistance_max_cell_number:
      name: "cell resistance max cell number"      
      device_id: bms_device_0
    cell_voltage_01:
      name: "cell voltage 01"
      device_id: bms_device_0
    cell_voltage_02:
      name: "cell voltage 02"
      device_id: bms_device_0
    cell_voltage_03:
      name: "cell voltage 03"
      device_id: bms_device_0
    cell_voltage_04:
      name: "cell voltage 04"
      device_id: bms_device_0
    cell_voltage_05:
      name: "cell voltage 05"
      device_id: bms_device_0
    cell_voltage_06:
      name: "cell voltage 06"
      device_id: bms_device_0
    cell_voltage_07:
      name: "cell voltage 07"
      device_id: bms_device_0
    cell_voltage_08:
      name: "cell voltage 08"
      device_id: bms_device_0
    cell_voltage_09:
      name: "cell voltage 09"
      device_id: bms_device_0
    cell_voltage_10:
      name: "cell voltage 10"
      device_id: bms_device_0
    cell_voltage_11:
      name: "cell voltage 11"
      device_id: bms_device_0
    cell_voltage_12:
      name: "cell voltage 12"
      device_id: bms_device_0
    cell_voltage_13:
      name: "cell voltage 13"
      device_id: bms_device_0
    cell_voltage_14:
      name: "cell voltage 14"
      device_id: bms_device_0
    cell_voltage_15:
      name: "cell voltage 15"
      device_id: bms_device_0
    cell_voltage_16:
      name: "cell voltage 16"
      device_id: bms_device_0
    cell_resistance_01:
      name: "cell resistance 01"
      device_id: bms_device_0
    cell_resistance_02:
      name: "cell resistance 02"
      device_id: bms_device_0
    cell_resistance_03:
      name: "cell resistance 03"
      device_id: bms_device_0
    cell_resistance_04:
      name: "cell resistance 04"
      device_id: bms_device_0
    cell_resistance_05:
      name: "cell resistance 05"
      device_id: bms_device_0
    cell_resistance_06:
      name: "cell resistance 06"
      device_id: bms_device_0
    cell_resistance_07:
      name: "cell resistance 07"
      device_id: bms_device_0
    cell_resistance_08:
      name: "cell resistance 08"
      device_id: bms_device_0
    cell_resistance_09:
      name: "cell resistance 09"
      device_id: bms_device_0
    cell_resistance_10:
      name: "cell resistance 10"
      device_id: bms_device_0
    cell_resistance_11:
      name: "cell resistance 11"
      device_id: bms_device_0
    cell_resistance_12:
      name: "cell resistance 12"
      device_id: bms_device_0
    cell_resistance_13:
      name: "cell resistance 13"
      device_id: bms_device_0
    cell_resistance_14:
      name: "cell resistance 14"
      device_id: bms_device_0
    cell_resistance_15:
      name: "cell resistance 15"
      device_id: bms_device_0
    cell_resistance_16:
      name: "cell resistance 16"
      device_id: bms_device_0
    battery_voltage:
      name: "battery voltage"
      device_id: bms_device_0
    battery_current:
      name: "battery current"
      device_id: bms_device_0
    battery_power:
      name: "battery power"
      device_id: bms_device_0
    battery_power_charging:
      name: "battery power charging"
      device_id: bms_device_0
    battery_power_discharging:
      name: "battery power discharging"
      device_id: bms_device_0
    temperature_sensor_1:
      name: "temperature sensor 1"
      device_id: bms_device_0
    temperature_sensor_2:
      name: "temperature sensor 2"
      device_id: bms_device_0
    temperature_sensor_3:
      name: "temperature sensor 3"
      device_id: bms_device_0
    temperature_sensor_4:
      name: "temperature sensor 4"
      device_id: bms_device_0
    temperature_sensor_5:
      name: "temperature sensor 5"
      device_id: bms_device_0
    temperature_powertube:
      name: "temperature powertube"
      device_id: bms_device_0
    battery_capacity_state_of_charge:
      name: "battery capacity state of charge"
      device_id: bms_device_0
    battery_capacity_remaining:
      name: "battery capacity remaining"
      device_id: bms_device_0
    charging_cycles:
      name: "charging cycles"
      device_id: bms_device_0
    battery_capacity_total_charging_cycle:
      name: "battery capacity total charging cycle"
      device_id: bms_device_0
    battery_total_runtime:
      name: "battery total runtime"
      device_id: bms_device_0
    balancing_current:
      name: "balancing current"
      device_id: bms_device_0
    errors_bitmask:
      name: "errors bitmask"
      device_id: bms_device_0
    cell_count_real:
      name: "cell count real"                                                       
      device_id: bms_device_0
    smart_sleep_time:
      name: "smart sleep time"                              
      device_id: bms_device_0
    powertube_temperature_protection:
      name: "powertube temperature protection" 
      device_id: bms_device_0
    powertube_temperature_protection_recovery:
      name: "powertube temperature protection recovery"  
      device_id: bms_device_0
    battery_total_alarms_count:     
      name: "battery total alarms count"  
      device_id: bms_device_0
    battery_total_alarms_active:     
      name: "battery total alarms active"  
      device_id: bms_device_0
    emergency_time_countdown:
      name: "emergency time countdown"      
      device_id: bms_device_0
    battery_soh_valuation:    
      name: "battery soh valuation"
      device_id: bms_device_0
    discharging_overcurrent_protection_release_time:    
      name: "discharging overcurrent protection release time"
      device_id: bms_device_0
    discharging_short_circuit_protection_release_time:    
      name: "discharging short circuit protection release time"
      device_id: bms_device_0
    charging_overcurrent_protection_release_time:    
      name: "charging overcurrent protection release time"
      device_id: bms_device_0
    charging_short_circuit_protection_release_time:    
      name: "charging short circuit protection release time"
      device_id: bms_device_0
    cell_undervoltage_protection_release_time:    
      name: "cell undervoltage protection release time"
      device_id: bms_device_0
    cell_overvoltage_protection_release_time:    
      name: "cell overvoltage protection release time"
      device_id: bms_device_0


  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms1
    balancing_direction:
      name: "balancing direction"
      device_id: bms_device_1
    battery_capacity_setting:
      name: "battery capacity setting"
      device_id: bms_device_1
    cell_voltage_min:
      name: "cell voltage min"
      device_id: bms_device_1
    cell_voltage_max:
      name: "cell voltage max"
      device_id: bms_device_1
    cell_voltage_min_cell_number:
      name: "cell voltage min cell number"
      device_id: bms_device_1
    cell_voltage_max_cell_number:
      name: "cell voltage max cell number"
      device_id: bms_device_1
    cell_delta_voltage:
      name: "cell delta voltage"
      device_id: bms_device_1
    cell_average_voltage:
      name: "cell average voltage"
      device_id: bms_device_1
    cell_resistance_min:
      name: "cell resistance min"
      device_id: bms_device_1
    cell_resistance_max:
      name: "cell resistance max"      
      device_id: bms_device_1
    cell_resistance_min_cell_number:
      name: "cell resistance min cell number"
      device_id: bms_device_1
    cell_resistance_max_cell_number:
      name: "cell resistance max cell number"        
      device_id: bms_device_1
    cell_voltage_01:
      name: "cell voltage 01"
      device_id: bms_device_1
    cell_voltage_02:
      name: "cell voltage 02"
      device_id: bms_device_1
    cell_voltage_03:
      name: "cell voltage 03"
      device_id: bms_device_1
    cell_voltage_04:
      name: "cell voltage 04"
      device_id: bms_device_1
    cell_voltage_05:
      name: "cell voltage 05"
      device_id: bms_device_1
    cell_voltage_06:
      name: "cell voltage 06"
      device_id: bms_device_1
    cell_voltage_07:
      name: "cell voltage 07"
      device_id: bms_device_1
    cell_voltage_08:
      name: "cell voltage 08"
      device_id: bms_device_1
    cell_voltage_09:
      name: "cell voltage 09"
      device_id: bms_device_1
    cell_voltage_10:
      name: "cell voltage 10"
      device_id: bms_device_1
    cell_voltage_11:
      name: "cell voltage 11"
      device_id: bms_device_1
    cell_voltage_12:
      name: "cell voltage 12"
      device_id: bms_device_1
    cell_voltage_13:
      name: "cell voltage 13"
      device_id: bms_device_1
    cell_voltage_14:
      name: "cell voltage 14"
      device_id: bms_device_1
    cell_voltage_15:
      name: "cell voltage 15"
      device_id: bms_device_1
    cell_voltage_16:
      name: "cell voltage 16"
      device_id: bms_device_1
    cell_resistance_01:
      name: "cell resistance 01"
      device_id: bms_device_1
    cell_resistance_02:
      name: "cell resistance 02"
      device_id: bms_device_1
    cell_resistance_03:
      name: "cell resistance 03"
      device_id: bms_device_1
    cell_resistance_04:
      name: "cell resistance 04"
      device_id: bms_device_1
    cell_resistance_05:
      name: "cell resistance 05"
      device_id: bms_device_1
    cell_resistance_06:
      name: "cell resistance 06"
      device_id: bms_device_1
    cell_resistance_07:
      name: "cell resistance 07"
      device_id: bms_device_1
    cell_resistance_08:
      name: "cell resistance 08"
      device_id: bms_device_1
    cell_resistance_09:
      name: "cell resistance 09"
      device_id: bms_device_1
    cell_resistance_10:
      name: "cell resistance 10"
      device_id: bms_device_1
    cell_resistance_11:
      name: "cell resistance 11"
      device_id: bms_device_1
    cell_resistance_12:
      name: "cell resistance 12"
      device_id: bms_device_1
    cell_resistance_13:
      name: "cell resistance 13"
      device_id: bms_device_1
    cell_resistance_14:
      name: "cell resistance 14"
      device_id: bms_device_1
    cell_resistance_15:
      name: "cell resistance 15"
      device_id: bms_device_1
    cell_resistance_16:
      name: "cell resistance 16"
      device_id: bms_device_1
    battery_voltage:
      name: "battery voltage"
      device_id: bms_device_1
    battery_current:
      name: "battery current"
      device_id: bms_device_1
    battery_power:
      name: "battery power"
      device_id: bms_device_1
    battery_power_charging:
      name: "battery power charging"
      device_id: bms_device_1
    battery_power_discharging:
      name: "battery power discharging"
      device_id: bms_device_1
    temperature_sensor_1:
      name: "temperature sensor 1"
      device_id: bms_device_1
    temperature_sensor_2:
      name: "temperature sensor 2"
      device_id: bms_device_1
    temperature_sensor_3:
      name: "temperature sensor 3"
      device_id: bms_device_1
    temperature_sensor_4:
      name: "temperature sensor 4"
      device_id: bms_device_1
    temperature_sensor_5:
      name: "temperature sensor 5"      
      device_id: bms_device_1
    temperature_powertube:
      name: "temperature powertube"
      device_id: bms_device_1
    battery_capacity_state_of_charge:
      name: "battery capacity state of charge"
      device_id: bms_device_1
    battery_capacity_remaining:
      name: "battery capacity remaining"
      device_id: bms_device_1
    charging_cycles:
      name: "charging cycles"
      device_id: bms_device_1
    battery_capacity_total_charging_cycle:
      name: "battery capacity total charging cycle"
      device_id: bms_device_1
    battery_total_runtime:
      name: "battery total runtime"
      device_id: bms_device_1
    balancing_current:
      name: "balancing current"
      device_id: bms_device_1
    errors_bitmask:
      name: "errors bitmask"
      device_id: bms_device_1
    cell_count_real:
      name: "cell count real"                                     
      device_id: bms_device_1
    smart_sleep_time:
      name: "smart sleep time"                              
      device_id: bms_device_1
    powertube_temperature_protection:
      name: "powertube temperature protection" 
      device_id: bms_device_1
    powertube_temperature_protection_recovery:
      name: "powertube temperature protection recovery"  
      device_id: bms_device_1
    battery_total_alarms_count:     
      name: "battery total alarms count"  
      device_id: bms_device_1
    battery_total_alarms_active:     
      name: "battery total alarms active"           
      device_id: bms_device_1
    emergency_time_countdown:
      name: "emergency time countdown"
      device_id: bms_device_1
    battery_soh_valuation:    
      name: "battery soh valuation"
      device_id: bms_device_1
    discharging_overcurrent_protection_release_time:    
      name: "discharging overcurrent protection release time"
      device_id: bms_device_1
    discharging_short_circuit_protection_release_time:    
      name: "discharging short circuit protection release time"
      device_id: bms_device_1
    charging_overcurrent_protection_release_time:    
      name: "charging overcurrent protection release time"
      device_id: bms_device_1
    charging_short_circuit_protection_release_time:    
      name: "charging short circuit protection release time"
      device_id: bms_device_1
    cell_undervoltage_protection_release_time:    
      name: "cell undervoltage protection release time"
      device_id: bms_device_1
    cell_overvoltage_protection_release_time:    
      name: "cell overvoltage protection release time"
      device_id: bms_device_1

text_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms0
    errors:
      name: "bms errors"
      device_id: bms_device_0
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms1
    errors:
      name: "bms errors"
      device_id: bms_device_1
      
binary_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms0
    status_charging:
      name: "status charging"
      device_id: bms_device_0
    status_discharging:
      name: "status discharging"
      device_id: bms_device_0
    status_balancing:
      name: "status balancing"
      device_id: bms_device_0
      
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms1
    status_charging:
      name: "status charging"
      device_id: bms_device_1
    status_discharging:
      name: "status discharging"
      device_id: bms_device_1
    status_balancing:
      name: "status balancing"
      device_id: bms_device_1

      
